# Generated by Django 2.2 on 2020-12-20 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('giohang', '__first__'),
        ('thanhvien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hoadon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thanhtoan', models.IntegerField(default=0)),
                ('thanhtien', models.FloatField(default=0)),
                ('giohang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giohang.giohang')),
                ('thanhvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thanhvien.thanhvien')),
            ],
        ),
    ]
