# Generated by Django 3.1.4 on 2020-12-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhachHang', '0002_auto_20201226_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
