# Generated by Django 2.2 on 2020-12-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KhachHang', '0004_auto_20201229_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='order',
            new_name='Order',
        ),
    ]
