# Generated by Django 2.2 on 2020-12-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhachHang', '0005_auto_20201230_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='trade_time',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='trade_time',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
