# Generated by Django 2.2 on 2020-12-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhachHang', '0006_auto_20201230_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
