# Generated by Django 2.2 on 2020-12-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KhachHang', '0007_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='trade_time',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
