# Generated by Django 2.2 on 2021-01-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KhachHang', '0010_auto_20210112_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='label',
        ),
    ]
