# Generated by Django 2.2 on 2021-01-12 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KhachHang', '0011_remove_product_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KhachHang.label'),
        ),
    ]
