# Generated by Django 2.2 on 2020-12-20 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loaihang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenloaihang', models.CharField(default='', max_length=255)),
                ('trangthai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='nganhhanh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tennganhhang', models.CharField(default='', max_length=255)),
                ('trangthai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='nhacungcap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tennhacungcap', models.CharField(default='', max_length=255)),
                ('diachinhacungcap', models.CharField(default='', max_length=255)),
                ('trangthai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='sanpham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tensanpham', models.CharField(default='', max_length=255)),
                ('giatien', models.FloatField(default=0.0)),
                ('soluong', models.IntegerField(default=0)),
                ('anh', models.ImageField(upload_to='')),
                ('mota', models.CharField(default='', max_length=500)),
                ('trangthai', models.BooleanField(default=True)),
                ('loaihang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sanpham.loaihang')),
                ('nhacungcap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sanpham.nhacungcap')),
            ],
        ),
        migrations.AddField(
            model_name='loaihang',
            name='nganhhanh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.nganhhanh'),
        ),
    ]
