# Generated by Django 2.2 on 2020-12-20 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('thanhvien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='phanhoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaiphanhoi', models.IntegerField(choices=[(0, 'Khiếu nại'), (1, 'Báo cáo'), (2, 'Đánh giá')], default=0)),
                ('tieude', models.CharField(default='', max_length=255)),
                ('noidung', models.CharField(default='', max_length=255)),
                ('ngaygui', models.DateTimeField(null=True)),
                ('trangthai', models.IntegerField(choices=[(0, 'Đã xem'), (1, 'Chưa xem'), (2, 'Đã phản hồi')], default=1)),
                ('nguoiphanhoi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='thanhvien.thanhvien')),
            ],
        ),
    ]
