# Generated by Django 2.2 on 2020-12-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='thanhvien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tendangnhap', models.CharField(max_length=255, null=True)),
                ('matkhau', models.CharField(max_length=255, null=True)),
                ('hovaten', models.CharField(max_length=255)),
                ('sodienthoai', models.CharField(max_length=11, null=True)),
                ('diachi', models.CharField(default='', max_length=255)),
                ('avatar', models.ImageField(upload_to='')),
                ('gioitinh', models.IntegerField(choices=[(0, 'Nữ'), (1, 'Nam')], default=0)),
                ('ngaydangky', models.DateTimeField(auto_now_add=True, null=True)),
                ('ngaysinh', models.DateTimeField(null=True)),
                ('trangthai', models.BooleanField(default=True)),
            ],
        ),
    ]
